required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/gengo/args",
  "k8s.io/gengo/generator",
  "k8s.io/gengo/examples/defaulter-gen/generators",
  "k8s.io/code-generator/cmd/defaulter-gen/args",
  "k8s.io/code-generator/cmd/deepcopy-gen/args"
]

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.6"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "v0.17.3"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  go-tests = false
  non-go = false
